<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'App\\Controller\\Controller' => 'get5bd3ddf8c496e203440813',
  'SubEntry5bd3ddf8c4d60' => 'get5bd3ddf8c4d63816453042',
  'App\\Controller\\HomeController' => 'get5bd3ddf8c4d80339664067',
  'SubEntry5bd3ddf8c4d8c' => 'get5bd3ddf8c4d8d975462109',
  'App\\Controller\\AuthController' => 'get5bd3ddf8c4dad103650045',
  'SubEntry5bd3ddf8c4db7' => 'get5bd3ddf8c4db8747272216',
  'Core\\Database\\DatabaseInterface' => 'get5bd3ddf8c4dc2539165582',
  'SubEntry5bd3ddf8c4dcb' => 'get5bd3ddf8c4dcc029294339',
  'SubEntry5bd3ddf8c4dd9' => 'get5bd3ddf8c4dda710958585',
  'SubEntry5bd3ddf8c4de9' => 'get5bd3ddf8c4dea722281640',
  'Nyholm\\Psr7\\Factory\\Psr17Factory' => 'get5bd3ddf8c4e07057846559',
);

    protected function get5bd3ddf8c4d63816453042()
    {
        $object = new Nyholm\Psr7\Factory\Psr17Factory();
        return $object;
    }

    protected function get5bd3ddf8c496e203440813()
    {
        $object = new App\Controller\Controller($this->get5bd3ddf8c4d63816453042());
        return $object;
    }

    protected function get5bd3ddf8c4d8d975462109()
    {
        return $this->delegateContainer->get('Nyholm\\Psr7\\Factory\\Psr17Factory');
    }

    protected function get5bd3ddf8c4d80339664067()
    {
        $object = new App\Controller\HomeController($this->get5bd3ddf8c4d8d975462109());
        return $object;
    }

    protected function get5bd3ddf8c4db8747272216()
    {
        return $this->delegateContainer->get('Core\\Database\\DatabaseInterface');
    }

    protected function get5bd3ddf8c4dad103650045()
    {
        $object = new App\Controller\AuthController($this->get5bd3ddf8c4db8747272216());
        return $object;
    }

    protected function get5bd3ddf8c4dda710958585()
    {
                $value = getenv('DB_USER');
        if (false !== $value) return $value;
        if (!false) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'DB_USER' has not been defined");
        }
        return NULL;
    }

    protected function get5bd3ddf8c4dea722281640()
    {
                $value = getenv('DB_PASS');
        if (false !== $value) return $value;
        if (!false) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'DB_PASS' has not been defined");
        }
        return NULL;
    }

    protected function get5bd3ddf8c4dcc029294339()
    {
        $object = new PDO('mysql:host=localhost;port=3306;dbname=phppsr;charset=utf8mb4', $this->get5bd3ddf8c4dda710958585(), $this->get5bd3ddf8c4dea722281640(), NULL);
        return $object;
    }

    protected function get5bd3ddf8c4dc2539165582()
    {
        $object = new Core\Database\EasydbDatabase($this->get5bd3ddf8c4dcc029294339());
        return $object;
    }

    protected function get5bd3ddf8c4e07057846559()
    {
        $object = new Nyholm\Psr7\Factory\Psr17Factory();
        return $object;
    }

}
