<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Nyholm\\Psr7\\Factory\\Psr17Factory' => 'get5bd3efba1d0e1646237020',
  'psr17factory' => 'get5bd3efba1d298182226545',
  'App\\Controller\\Controller' => 'get5bd3efba1d2aa090787218',
  'SubEntry5bd3efba1d2b9' => 'get5bd3efba1d2ba488338706',
  'App\\Controller\\HomeController' => 'get5bd3efba1d2c4139730428',
  'SubEntry5bd3efba1d2ce' => 'get5bd3efba1d2cf435432485',
  'App\\Controller\\AuthController' => 'get5bd3efba1d2d7573421872',
  'SubEntry5bd3efba1d2de' => 'get5bd3efba1d2df063227135',
  'SubEntry5bd3efba1d2e3' => 'get5bd3efba1d2e4702080790',
  'Core\\Database\\DatabaseInterface' => 'get5bd3efba1d2eb339572102',
  'SubEntry5bd3efba1d2f2' => 'get5bd3efba1d2f3156345909',
  'SubEntry5bd3efba1d2fc' => 'get5bd3efba1d2fd854420342',
  'SubEntry5bd3efba1d30a' => 'get5bd3efba1d30b300117120',
);

    protected function get5bd3efba1d0e1646237020()
    {
        $object = new Nyholm\Psr7\Factory\Psr17Factory();
        return $object;
    }

    protected function get5bd3efba1d298182226545()
    {
        return $this->delegateContainer->get('Nyholm\\Psr7\\Factory\\Psr17Factory');
    }

    protected function get5bd3efba1d2ba488338706()
    {
        return $this->delegateContainer->get('psr17factory');
    }

    protected function get5bd3efba1d2aa090787218()
    {
        $object = new App\Controller\Controller($this->get5bd3efba1d2ba488338706());
        return $object;
    }

    protected function get5bd3efba1d2cf435432485()
    {
        return $this->delegateContainer->get('Nyholm\\Psr7\\Factory\\Psr17Factory');
    }

    protected function get5bd3efba1d2c4139730428()
    {
        $object = new App\Controller\HomeController($this->get5bd3efba1d2cf435432485());
        return $object;
    }

    protected function get5bd3efba1d2df063227135()
    {
        return $this->delegateContainer->get('Core\\Database\\DatabaseInterface');
    }

    protected function get5bd3efba1d2e4702080790()
    {
        return $this->delegateContainer->get('psr17factory');
    }

    protected function get5bd3efba1d2d7573421872()
    {
        $object = new App\Controller\AuthController($this->get5bd3efba1d2df063227135(), $this->get5bd3efba1d2e4702080790());
        return $object;
    }

    protected function get5bd3efba1d2fd854420342()
    {
                $value = getenv('DB_USER');
        if (false !== $value) return $value;
        if (!false) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'DB_USER' has not been defined");
        }
        return NULL;
    }

    protected function get5bd3efba1d30b300117120()
    {
                $value = getenv('DB_PASS');
        if (false !== $value) return $value;
        if (!false) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'DB_PASS' has not been defined");
        }
        return NULL;
    }

    protected function get5bd3efba1d2f3156345909()
    {
        $object = new PDO('mysql:host=localhost;port=3306;dbname=phpinas;charset=utf8mb4', $this->get5bd3efba1d2fd854420342(), $this->get5bd3efba1d30b300117120(), NULL);
        return $object;
    }

    protected function get5bd3efba1d2eb339572102()
    {
        $object = new Core\Database\EasydbDatabase($this->get5bd3efba1d2f3156345909());
        return $object;
    }

}
